### ISSUE TITLE
Put Odo Under the Umbrella

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#396]
Put Odo Under the Umbrella

- [ ] Archive Old Repo
- [ ] Migrate code and git history to `smartcitiesdata` 
- [ ] All tests pass
- [ ] Add to E2E tests
- [ ] Deploy to Production
